name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm run test
    - name: Check code coverage
      run: npm run coverage
    - name: Lint code
      run: npm run lint
    - name: Format code
      run: npm run format
    - name: Build project
      run: npm run build
    - name: Generate documentation
      run: npm run docs
